#!/bin/bash
set -e
DB="$1"
COMMIT_MSG="$2"

if [[ -z "$1" ]]; then
  error_log "Nonexistent database"
  exit 1
fi

if ! [[ -d /var/db/dino/"$DB"/.git ]]; then
  error_log "Database not using git"
  exit 1
fi

cd /var/db/dino/"$DB"
git add . || {
  error_log "Could not git add"
  exit 1
}

if [[ -n "$COMMIT_MSG" ]]; then
  git commit -m "$COMMIT_MSG" || {
	error_log "Could not git commit"
	exit 1
  }
else
  git commit -m "Updated database $DB" || {
	error_log "Could not git commit"
	exit 1
  }
fi
