#!/bin/bash
set -e
DB="$1"
PROMPT="$2"
if [[ -z "$1" ]]; then
  error_log "No input given"
fi

if [[ -n "$PROMPT" ]]; then
  echo -n "Are you sure you want to remove $DB [y/N] "
  read -r answer
  if [[ "$answer" == "y" ]]; then
	rm -rfv "/var/db/dino/${DB:?}/" || {
	  error_log "Could not remove database"
	  exit 1
	}
  else
	exit 1
  fi
else
  rm -rfv "/var/db/dino/${DB:?}/" || {
    error_log "Could not remove database"
    exit 1
  }
fi
