#!/bin/bash
set -e
DB="$1"
PROMPT="$2"
if [[ -z "$1" ]]; then
  echo "No input given" > "$TMP_ERROR_REASON"
fi

if [[ -n "$PROMPT" ]]; then
  echo -n "Are you sure you want to remove $DB [y/N] "
  read -r answer
  if [[ "$answer" == "y" ]]; then
	rm -rfv "/var/db/dino/${DB:?}/" || {
	  echo "Could not remove database" > "$TMP_ERROR_REASON"
	  exit 1
	}
  else
	exit 1
  fi
else
  rm -rfv "/var/db/dino/${DB:?}/" || {
	echo "Could not remove database" > "$TMP_ERROR_REASON"
	exit 1
  }
fi
