#!/bin/bash
set -e
DB="$1"
if [[ -z "$1" ]]; then
  error_log "No input given"
  exit 1
fi

if ! [[ -d /var/db/dino/"$DB" ]]; then
  error_log "Nonexistent database"
  exit 1
fi

zip -r "$DB".zip /var/db/dino/"$DB" || {
  error_log "Failed to export database"
  exit 1
}
