#!/bin/bash
set -e
DB="$1"
if [[ -z "$1" ]]; then
  echo "No input given" > "$TMP_ERROR_REASON"
  exit 1
fi

if ! [[ -d /var/db/dino/"$DB" ]]; then
  echo "Nonexistent database" > "$TMP_ERROR_REASON"
  exit 1
fi

zip -r "$DB".zip /var/db/dino/"$DB" || {
  echo "Failed to export database" > "$TMP_ERROR_REASON"
  exit 1
}
