#!/bin/bash
set -e
DB=$1
FIELD="$2"
ITEM="$3"
# We want to ls the database is metadata isn't specified, but if it is, cat the file
if [[ -z "$1" ]]; then
  echo "No input given" > "$TMP_ERROR_REASON"
  exit 1
fi

if ! [[ -d /var/db/dino/"$DB" ]]; then
  echo "Nonexistent database" > "$TMP_ERROR_REASON"
  exit 1
fi


if [[ -z "$FIELD" ]]; then
  ls -1aA --ignore='.git' /var/db/dino/"$DB"
  exit
fi
if [[ -z "$ITEM" ]]; then
  ls -1aA --ignore='.git' /var/db/dino/"$DB"/"$FIELD"
  exit
fi
cat /var/db/dino/"$DB"/"$FIELD"/"$ITEM" || {
  echo "Nonexistent item" > "$TMP_ERROR_REASON"
  exit 1
}
exit
