#!/bin/bash
set -e
DB="$1"
if [[ "$1" == "git" ]]; then
  error_log "No input provided"
  exit 1
fi

# Check if DB exists
if ! [[ -d /var/db/dino/"$DB" ]]; then
  error_log "Non existent database"
  exit 1
fi
# Check if it has a .git dir
if ! [[ -d /var/db/dino/"$DB"/.git ]]; then
  git init -q /var/db/dino/"$DB" || {
    error_log "Could not create git directory"
    exit 1
}
else
  echo "Git directory already exists. Did you mean COMMIT?"
  exit 1
fi
