#!/bin/bash
echo -e "${bold}CREATE${normal} foo"
echo -e "\tShould create the database \`foo\`"
echo -e "${bold}SETUP${normal} foo names"
echo -e "\tShould setup the database foo with the field \`names\`"
echo -e "${bold}GET${normal} foo names"
echo -e "\tShould list out all fields in database \`foo\`"
echo -e "${bold}INSERT${normal} foo names Henry 16"
echo -e "\tShould create an item in the \`names\` field called \`Henry\` with the metadata \`16\`"
echo -e "${bold}GET${normal} foo names Henry"
echo -e "\tShould return \`16\`"
echo -e "${bold}TESTING${normal} anytext"
echo -e "\tFor debugging purposes"
exit
