#!/bin/bash
echo -e "${bold}CREATE${normal} foo"
echo -e "\t-- Create the database \`foo\`"
echo -e "${bold}SETUP${normal} foo names"
echo -e "\t-- Setup the database foo with the field \`names\`"
echo -e "${bold}GET${normal} foo names"
echo -e "\t-- List out all fields in database \`foo\`"
echo -e "${bold}INSERT${normal} foo names Henry 16"
echo -e "\t-- Create an item in the \`names\` field called \`Henry\` with the metadata \`16\`"
echo -e "${bold}GET${normal} foo names Henry"
echo -e "\t-- Will return \`16\`"
echo -e "${bold}TESTING${normal} anytext"
echo -e "\t-- For debugging purposes"
exit
