#!/bin/bash
set -e
DB="$1"
FIELD="$2"
ITEM="$3"
METADATA="$4"

if ! [[ -d /var/db/dino/"$DB" ]]; then
  error_log "Non existent database"
  exit 1
fi

if ! [[ -d /var/db/dino/"$DB"/"$FIELD" ]]; then
  error_log "Non existent field"
  exit 1
fi

if [[ -z "$ITEM" ]]; then
  error_log "item empty"
  exit 1
fi
if [[ -z "$METADATA" ]]; then
  error_log "metadata empty"
  exit 1
fi

rm -vI --preserve-root /var/db/dino/"$DB"/"$FIELD"/"$ITEM"
