#!/bin/bash
set -e
DB="$1"
COMMITID="$2"

if [[ -z "$1" ]]; then
  error_log "No input given"
  exit 1
fi

if ! [[ -d /var/db/dino/"$DB"/.git ]]; then
  error_log "Database not using git"
  exit 1
fi

cd /var/db/dino/"$DB"
if [[ -n "$COMMITID" ]]; then
  git reset --hard "$COMMITID"
else
  git reflog
  echo -n "Which commit id? "
  read -r commit
  git reset --hard "$commit"
fi
