#!/bin/bash
set -e
DB="$1"
FIELD="$2"

if ! [[ -d /var/db/dino/"$DB" ]]; then
  error_log "Non existent database"
  exit 1
fi

mkdir -pv /var/db/dino/"$DB"/"$FIELD" || {
  error_log "Could not create field"
  exit 1
}
